apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: user-jwbgb
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: 2018-10-26T09:44:01Z
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: apospublicuploads
  namespace: default
  resourceVersion: "7540"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/apospublicuploads
  uid: ab2d5101-d903-11e8-b005-fa163e3f7016
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: apos-publicuploads
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
