apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-jwbgb
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-bh8g2:m-6954d2b61642","addresses":["192.168.2.106"],"port":4000,"protocol":"TCP","podName":"default:aoi-pdfprinter-c49847954-ckcbh","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2","field.cattle.io/creatorId":"user-jwbgb","field.cattle.io/publicEndpoints":"[{\"nodeName\":\"c-8pc2n:m-6954d2b61642\",\"addresses\":[\"192.168.2.34\"],\"port\":4000,\"protocol\":\"TCP\",\"podName\":\"default:aoi-pdfprinter-79fbc66479-p59tq\",\"allNodes\":false}]"},"creationTimestamp":null,"generation":1,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-default-aoi-pdfprinter"},"name":"aoi-pdfprinter","namespace":"default","selfLink":"/apis/apps/v1beta2/namespaces/default/deployments/aoi-pdfprinter"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-default-aoi-pdfprinter"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2019-02-21T16:08:52Z","field.cattle.io/ports":"[[{\"containerPort\":4000,\"dnsName\":\"aoi-pdfprinter-hostport\",\"hostPort\":4000,\"kind\":\"HostPort\",\"name\":\"4000tcp40000\",\"protocol\":\"TCP\",\"sourcePort\":4000}]]","workload.cattle.io/state":"{\"cGNwLXNydjA2\":\"c-8pc2n:m-6954d2b61642\"}"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-default-aoi-pdfprinter"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"4000"}],"image":"francescoronci/aoi-pdfprinter:0.1","imagePullPolicy":"Always","name":"aoi-pdfprinter","ports":[{"containerPort":4000,"hostPort":4000,"name":"4000tcp40000","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true}],"dnsPolicy":"ClusterFirst","nodeName":"pcp-srv06","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{}}'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-aoi-pdfprinter
  name: aoi-pdfprinter
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/aoi-pdfprinter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-aoi-pdfprinter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-04-19T16:10:36Z"
        field.cattle.io/ports: '[[{"containerPort":4000,"dnsName":"aoi-pdfprinter-hostport","hostPort":4000,"kind":"HostPort","name":"4000tcp40000","protocol":"TCP","sourcePort":4000}]]'
        workload.cattle.io/state: '{"":"c-8pc2n:m-6954d2b61642","cGNwLXNydjA2":"c-8pc2n:m-6954d2b61642"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-aoi-pdfprinter
    spec:
      containers:
      - env:
        - name: PORT
          value: "4000"
        image: francescoronci/aoi-pdfprinter:0.1
        imagePullPolicy: Always
        name: aoi-pdfprinter
        ports:
        - containerPort: 4000
          hostPort: 4000
          name: 4000tcp40000
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeName: pcp-srv06
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
