apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-bh8g2:m-9eb5e579a6b3","addresses":["192.168.2.105"],"port":27017,"protocol":"TCP","podName":"default:mongodb-nqmbq-56ffd64f6d-m6hch","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2018-10-24T15:00:35Z","generation":1,"labels":{"app":"mongodb","chart":"mongodb-4.6.2","heritage":"Tiller","io.cattle.field/appId":"mongodb-nqmbq","release":"mongodb-nqmbq"},"name":"mongodb-nqmbq","namespace":"default","resourceVersion":"37828","selfLink":"/apis/apps/v1beta2/namespaces/default/deployments/mongodb-nqmbq","uid":"8f6f70d6-d79d-11e8-b230-fa163e8ea547"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"mongodb","release":"mongodb-nqmbq"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"mongodb","chart":"mongodb-4.6.2","release":"mongodb-nqmbq"}},"spec":{"containers":[{"env":[{"name":"MONGODB_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mongodb-root-password","name":"mongodb-nqmbq"}}},{"name":"MONGODB_USERNAME"},{"name":"MONGODB_DATABASE"},{"name":"MONGODB_ENABLE_IPV6","value":"yes"},{"name":"MONGODB_EXTRA_FLAGS"},{"name":"MONGODB_ENABLE_IPV6","value":"yes"}],"image":"docker.io/bitnami/mongodb:4.0.3","imagePullPolicy":"Always","livenessProbe":{"exec":{"command":["mongo","--eval","db.adminCommand(''ping'')"]},"failureThreshold":6,"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"mongodb-nqmbq","ports":[{"containerPort":27017,"name":"mongodb","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["mongo","--eval","db.adminCommand(''ping'')"]},"failureThreshold":6,"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/bitnami/mongodb","name":"data"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":0,"runAsUser":0},"terminationGracePeriodSeconds":30,"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"mongovolume"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2018-10-24T15:00:35Z","lastUpdateTime":"2018-10-24T15:00:35Z","message":"Deployment
      has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2018-10-24T15:00:35Z","lastUpdateTime":"2018-10-24T15:00:45Z","message":"ReplicaSet
      \"mongodb-nqmbq-867976f764\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}'
  creationTimestamp: null
  generation: 1
  labels:
    app: mongodb
    chart: mongodb-4.6.2
    heritage: Tiller
    io.cattle.field/appId: mongodb-nqmbq
    release: mongodb-nqmbq
  name: mongodb-nqmbq
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/mongodb-nqmbq
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb
      release: mongodb-nqmbq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-04-19T15:22:38Z"
        field.cattle.io/ports: '[[{"containerPort":27017,"dnsName":"mongodb-nqmbq-hostport","hostPort":27017,"kind":"HostPort","name":"mongodb","protocol":"TCP","sourcePort":27017}]]'
        workload.cattle.io/state: '{"cGNwLXNydjA1":"c-bh8g2:m-9eb5e579a6b3"}'
      creationTimestamp: null
      labels:
        app: mongodb
        chart: mongodb-4.6.2
        release: mongodb-nqmbq
    spec:
      containers:
      - env:
        - name: MONGODB_DATABASE
        - name: MONGODB_ENABLE_IPV6
          value: "yes"
        - name: MONGODB_EXTRA_FLAGS
        - name: MONGODB_USERNAME
        - name: MONGODB_ROOT_PASSWORD
        image: docker.io/bitnami/mongodb:4.0.3
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongodb-nqmbq
        ports:
        - containerPort: 27017
          hostPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          capabilities: {}
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/mongodb/data/db
          name: data
      dnsPolicy: ClusterFirst
      nodeName: pcp-srv05
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongovol
status: {}
